version: '3.4'

services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5105:80"

  microservices.webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://10.0.75.1:5105 
      - ASPNETCORE_HTTPS_PORT=44353                 
      - CatalogUrlHC=https://www.google.es 
    ports:
      - "5100:80"
