version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo

  basket.data:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity.api:
    image: eshop/identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile    
    depends_on:
      - sql.data