version: '3.4'

services:
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src\Services\Identity\Identity.API\Dockerfile

  microservices.webmvc:
    image: ${DOCKER_REGISTRY-}microserviceswebmvc
    build:
      context: .
      dockerfile: src\Web\Microservices.WebMVC\Dockerfile
